FROM openjdk:8u212-jre
MAINTAINER cwh 764471698@qq.com

COPY ./target/platform-gateway-1.0-RELEASE.jar /platform/platform-gateway-1.4-RELEASE.jar

ENTRYPOINT ["java", "-jar", "/platform/platform-gateway-1.0-RELEASE.jar"]